# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/*.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.py'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Super-Linter
    #   uses: super-linter/super-linter@v5.3.1
    #   env:
    #       VALIDATE_ALL_CODEBASE: false
    #       DEFAULT_BRANCH: main
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
            
    - name: Test with pytest
      run: |
        pytest
